### ISSUE TITLE
feat: support for python3.11

### ISSUE THREAD

**Issue by madebylydia** [Predeactor/discapty#9]
Known blocking dependencies: python-pillow/Pillow#6460
Should be resolved: ~~October 15, 2022~~ Delayed to October 24, 2022.
With version: 9.3.0

**Comment by radarhere** [comment]
Python 3.11 itself has been [delayed until October 24](https://blog.python.org/2022/09/python-3110rc2-is-now-available.html), so Pillow's support for it will be similarly delayed.

**Comment by madebylydia** [comment]
Python 3.11 is now supported in version 2.1.2 of DisCapTy.
